name: wf
on:
  pull_request:
      branches:
        - develop
  push:
      branches:
        - develop
jobs:
  linting-jobs:
      runs-on: ubuntu-latest
      steps:
        - name: WELCOME STEP
          run: echo "Something"
        - name: checkout repo
          uses: actions/checkout@V4
        - name: install htmlhint
          run: npm --save-dev htmlhint
        - name: install stylelint
          run: npm --save-dev stylelint
        - name: lint html files
          run: npm htmlhint "**/*.html"
        - name: lint stylelint files
          run: npm stylelint "**/.css"
        - name: Display package.json contents
          run: cat package.json
